export interface BacklogElement {
    id?: number; // generated by the backend
    title: string;
    description: string;
    creationDate?: Date; // could be generated
    levelId: number;
    userId: number;
    typeId: number;
    metadata: Map<string, string>;
}

export declare type BacklogElements = BacklogElement[];



export interface LocalBacklogElement extends BacklogElement {
    content: string;
}


export interface RemoteBacklogElement extends BacklogElement {
    content?: File;
    url: string;
    transcription?: string;
}


export interface DocumentElement extends BacklogElement {
    content: string;
}

export interface ImageElement extends BacklogElement {
    url: string;
    transcription: string;
}

export interface VideoElement extends BacklogElement {
    url: string;
    transcription: string;
}

